// <auto-generated />
namespace CourseWork.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class noC3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(noC3));
        
        string IMigrationMetadata.Id
        {
            get { return "202205151742319_noC3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
