CREATE TABLE PRODUCT_CATEGORY (
	ID INT IDENTITY(1,1) NOT NULL,

	NAME NVARCHAR(100) NOT NULL,

	CONSTRAINT PK_PRODUCT_CATEGORY_ID PRIMARY KEY CLUSTERED (ID)
)

CREATE TABLE PRODUCT (
	ID INT IDENTITY(1,1) NOT NULL,

	NAME VARCHAR(100) NOT NULL,
	PRICE MONEY NOT NULL DEFAULT 0,

	PRODUCT_CATEGORY_ID INT NOT NULL,

	CONSTRAINT PK_PRODUCT_ID PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_PRODUCT_PRODUCT_CATEGORY FOREIGN KEY (PRODUCT_CATEGORY_ID) 
		REFERENCES PRODUCT_CATEGORY (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

	CONSTRAINT CHK_PRODUCT_PRICE
		CHECK (PRICE > 0)
)

ALTER TABLE PRODUCT
	ADD IS_DELETED BIT NOT NULL DEFAULT 0


CREATE TABLE LOCATION (
	ID INT IDENTITY(1,1) NOT NULL,
	
	COUNTRY_CODE NVARCHAR(100) NOT NULL,
	LOCATION_1 NVARCHAR(100) NULL,
	LOCATION_2 NVARCHAR(100) NULL,
	LOCATION_3 NVARCHAR(100) NULL,

	CONSTRAINT PK_LOCATION_ID PRIMARY KEY CLUSTERED (ID),
)

CREATE TABLE WAREHOUSE (
	ID INT IDENTITY(1,1) NOT NULL,

	NAME NVARCHAR(100) NOT NULL,
	LOCATION_ID INT NOT NULL,

	CONSTRAINT PK_WAREHOUSE_ID PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_WAREHOUSE_LOCATION_ID FOREIGN KEY (LOCATION_ID)
		REFERENCES LOCATION (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
)

CREATE TABLE HISTORY_TYPE (
	ID INT IDENTITY(1,1) NOT NULL,

	NAME VARCHAR(100) NOT NULL,

	CONSTRAINT PK_HISTORY_TYPE_ID PRIMARY KEY CLUSTERED (ID),
)

CREATE TABLE HISTORY (
	ID INT IDENTITY(1,1) NOT NULL,
	
	DATE DATETIME NOT NULL DEFAULT GETDATE(),
	HISTORY_TYPE_ID INT NOT NULL,
	IS_DELETED BIT NOT NULL DEFAULT 0,
	
	CONSTRAINT PK_HISOTRY_ID PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_HISTORY_HISTORY_TYPE_ID FOREIGN KEY (HISTORY_TYPE_ID)
		REFERENCES HISTORY_TYPE (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
)

CREATE TABLE HISTORY_PRODUCT (
	HISTORY_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,

	COUNT INT NOT NULL DEFAULT 0,

	CONSTRAINT PK_HISTORY_PRODUCT PRIMARY KEY CLUSTERED (HISTORY_ID, PRODUCT_ID),
	CONSTRAINT FK_HISTORY_PRODUCT_HISTORY_ID FOREIGN KEY (HISTORY_ID)
		REFERENCES HISTORY (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT FK_HISTORY_PRODUCT_PRODUCT_ID FOREIGN KEY (PRODUCT_ID)
		REFERENCES PRODUCT (ID) 
		ON DELETE CASCADE
		ON UPDATE CASCADE,
)

CREATE TABLE WAREHOUSE_PRODUCT (
	WAREHOUSE_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,

	CONSTRAINT PK_WAREHOUSE_PRODUCT_I PRIMARY KEY CLUSTERED (WAREHOUSE_ID, PRODUCT_ID),
	CONSTRAINT FK_WAREHOUSE_PRODUCT_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_ID)
		REFERENCES WAREHOUSE (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT FK_WAREHOUSE_PRODUCT_PRODUCT_ID FOREIGN KEY (PRODUCT_ID)
		REFERENCES PRODUCT (ID) 
		ON DELETE CASCADE
		ON UPDATE CASCADE,
)

GO
DROP TYPE PRODUC_LIST_TYPE;
GO
CREATE TYPE PRODUCT_LIST_TYPE AS TABLE
(
	PRODUCT_ID INT NOT NULL,
	AMOUNT INT NOT NULL
);