CREATE OR ALTER FUNCTION GET_WAREHOUSE_STORED_INFO (@WAREHOUSE_ID INT)
RETURNS TABLE
AS 
RETURN (
	SELECT * FROM WAREHOUSES WHERE ID = @WAREHOUSE_ID
)

CREATE OR ALTER FUNCTION GET_PRODUCTS_BY_CATEGORY (@CATEGORY_ID INT)
RETURNS TABLE
AS 
RETURN (
	SELECT * FROM PRODUCTS WHERE PRODUCT_CATEGORY_ID = @CATEGORY_ID AND IS_DELETED = 0
)

CREATE OR ALTER FUNCTION GET_HISTORY_BY_CATEGORY (@HISTORY_TYPE INT)
RETURNS TABLE
AS 
RETURN (
	SELECT * FROM HISTORIES WHERE HISTORY_TYPE_ID = @HISTORY_TYPE AND IS_DELETED = 0
)
