INSERT INTO PRODUCT_CATEGORIES
VALUES ('TEST CATEGORY 1'),
	('TEST CATEGORY 2')

GO 

INSERT INTO PRODUCTS (NAME, PRODUCT_CATEGORY_ID, PRICE)
VALUES ('TEST PRODUCT 1', 1, 10),
	('TEST PRODUCT 2', 1, 10),
	('TEST PRODUCT 3', 1, 10),
	('TEST PRODUCT 4', 1, 10),
	('TEST PRODUCT 5', 1, 10)

GO

INSERT INTO LOCATIONS(COUNTRY_CODE, LOCATION_1, LOCATION_2)
VALUES ('BY', 'MINSK', '...')

GO

INSERT INTO WAREHOUSES(NAME, LOCATION_ID)
VALUES ('TEST WAREHOUSE', 1);

GO
INSERT INTO HISTORY_TYPES(NAME)
VALUES ('SUPPLIES'),('SALES')