ALTER PROCEDURE CREATE_HISTORY
	@HISTORY_TYPE_ID INT ,
	@DATE DATETIME,
	@HISTORY_ID INT OUTPUT
AS 
BEGIN 
	INSERT INTO HISTORY (DATE, HISTORY_TYPE_ID)
	VALUES (@DATE, @HISTORY_TYPE_ID)

	SET @HISTORY_ID = SCOPE_IDENTITY();
	
END

ALTER PROCEDURE NEW_HISTORY_EVENT
	@PRODUCT_ITEMS PRODUCT_LIST_TYPE READONLY,	
	@HISTORY_TYPE_ID INT,
	@DATE DATETIME
AS
BEGIN

	DECLARE @HISTORY_ID INT;
	EXECUTE CREATE_HISTORY @HISTORY_TYPE_ID, @DATE, @HISTORY_ID OUTPUT;

	INSERT INTO HISTORY_PRODUCT (PRODUCT_ID, HISTORY_ID, COUNT)
	SELECT P.PRODUCT_ID, @HISTORY_ID, P.AMOUNT
	FROM @PRODUCT_ITEMS P

END;

