DECLARE @L PRODUCT_LIST_TYPE;

INSERT INTO @L
VALUES (1, 10), (2, 20), (3, 10), (4, 10);

DECLARE @DATE DATETIME = GETDATE();
EXECUTE NEW_HISTORY_EVENT @L, 1, @DATE

SELECT * FROM ACTUAL_FULL_HISTORY_WITH_PRODUCTS_VIEW

--INSERT INTO LOCATION
--INSERT INTO WAREHOUSE VALUES (