CREATE TRIGGER AFTER_INSERT_TRIGGER ON HISTORY_PRODUCT
FOR INSERT
AS
	DECLARE 
		@PRODUCT_ID INT,
		@WAREHOUSE_ID INT,
		@COUNT INT

	select @PRODUCT_ID = PRODUCT_ID FROM INSERTED;
	select @WAREHOUSE_ID = WAREHOUSE_ID FROM INSERTED;
	select @COUNT = COUNT FROM INSERTED;

	EXECUTE CHANGE_PRODUCT_WAREHOUSE_LINK @PRODUCT_ID, @WAREHOUSE_ID, @COUNT