CREATE TRIGGER AFTER_INSERT_TRIGGER ON HISTORY_PRODUCT
AFTER INSERT
AS
	DECLARE 
		@TEMP AS TABLE(
			ROW_N INT,
			PRODUCT_ID INT,

			WAREHOUSE_ID INT,
			COUNT INT
		)
	DECLARE
		@PRODUCT_ID INT,
		@WAREHOUSE_ID INT,
		@COUNT INT

	INSERT INTO @TEMP
	SELECT ROW_NUMBER() OVER(ORDER BY COUNT ASC), PRODUCT_ID, WAREHOUSE_ID, COUNT FROM INSERTED

	WHILE Exists
	(
		select 1 
		from @TEMP
	)
	begin
		declare @TEMP_ID INT;
	
		SELECT TOP 1 
			@TEMP_ID = ROW_N, 
			@PRODUCT_ID = PRODUCT_ID,
			@WAREHOUSE_ID = WAREHOUSE_ID,
			@COUNT = COUNT
		from @TEMP 

		EXECUTE CHANGE_PRODUCT_WAREHOUSE_LINK @PRODUCT_ID, @WAREHOUSE_ID, @COUNT

		delete 
		from @TEMP
		where ROW_N = @TEMP_ID
	end



	