ALTER VIEW ACTUAL_HISTORY_VIEW
AS 
SELECT ID, HISTORY_TYPE_ID, DATE
FROM HISTORY
WHERE IS_DELETED = 0

SELECT * FROM ACTUAL_HISTORY_VIEW

CREATE VIEW ACTUAL_FULL_HISTORY_VIEW
AS
SELECT H.ID, H.DATE, HP.NAME
FROM HISTORY H
LEFT JOIN HISTORY_TYPE HT ON H.HISTORY_TYPE_ID = HT.ID
WHERE H.IS_DELETED = 0