USE DB2
GO

ALTER VIEW ACTUAL_HISTORY_VIEW
AS 
SELECT ID, HISTORY_TYPE_ID, DATE
FROM HISTORIES
WHERE IS_DELETED = 0

GO 

SELECT * FROM ACTUAL_HISTORY_VIEW

GO

CREATE VIEW ACTUAL_FULL_HISTORY_VIEW
AS
SELECT H.ID, H.DATE, HT.NAME AS TYPE
FROM ACTUAL_HISTORY_VIEW H
LEFT JOIN HISTORY_TYPES HT ON H.HISTORY_TYPE_ID = HT.ID

GO 

SELECT * FROM ACTUAL_FULL_HISTORY_VIEW

GO

CREATE VIEW ACTUAL_FULL_HISTORY_WITH_PRODUCTS_VIEW
AS
SELECT H.ID AS HISTORY_ID, H.DATE, H.TYPE, P.ID AS PRODUCT_ID, P.NAME AS PRODUCT_NAME, P.PRICE, HP.COUNT
FROM ACTUAL_FULL_HISTORY_VIEW AS H
LEFT JOIN HISTORY_PRODUCT HP ON H.ID = HP.HISTORY_ID
LEFT JOIN PRODUCTS P ON P.ID = HP.PRODUCT_ID

GO

SELECT * FROM ACTUAL_FULL_HISTORY_WITH_PRODUCTS_VIEW