//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SweetShopEntities : DbContext
    {
        public SweetShopEntities()
            : base("Data Source=SIARHEI-KHARLAP\\SQLEXPRESS;Initial Catalog=SweetShop;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //modelBuilder.Entity<PRODUCT_CATEGORIES>().HasKey(pc => pc.ID);
            base.OnModelCreating(modelBuilder);
        }
    
        public DbSet<PRODUCT_CATEGORIES> PRODUCT_CATEGORIES { get; set; }
        public DbSet<PRODUCT> PRODUCTS { get; set; }
    }
}
