IF OBJECT_ID(N'secure.PRODUCTS') IS NOT NULL
	DROP TABLE secure.PRODUCTS
GO
IF OBJECT_ID(N'secure.PRODUCT_CATEGORIES') IS NOT NULL
	DROP TABLE secure.PRODUCT_CATEGORIES
GO

IF EXISTS (SELECT * FROM sys.schemas WHERE name = 'secure')
	DROP SCHEMA secure;
GO
CREATE SCHEMA secure
Go

CREATE TABLE secure.PRODUCT_CATEGORIES (
	ID INT IDENTITY(1,1) NOT NULL,

	NAME NVARCHAR(100) NOT NULL,
	IS_DELETED BIT NOT NULL DEFAULT 0,

	CONSTRAINT PK_PRODUCT_CATEGORY_ID PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE secure.PRODUCTS (
	ID INT IDENTITY(1,1) NOT NULL,

	NAME VARCHAR(100) NOT NULL,
	PRICE MONEY NOT NULL DEFAULT 0,

	PRODUCT_CATEGORY_ID INT NOT NULL,
	IS_DELETED BIT NOT NULL DEFAULT 0,

	CONSTRAINT PK_PRODUCT_ID PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_PRODUCT_PRODUCT_CATEGORY FOREIGN KEY (PRODUCT_CATEGORY_ID) 
		REFERENCES secure.PRODUCT_CATEGORIES (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

	CONSTRAINT CHK_PRODUCT_PRICE
		CHECK (PRICE > 0)
)
GO