CREATE OR ALTER VIEW PRODUCT_CATEGORIES
AS
	SELECT ID, NAME
	FROM secure.PRODUCT_CATEGORIES
	WHERE IS_DELETED = 0
GO

CREATE OR ALTER VIEW PRODUCTS
AS
	SELECT ID, NAME, PRICE, PRODUCT_CATEGORY_ID
	FROM secure.PRODUCTS
	WHERE IS_DELETED = 0
GO

