CREATE OR ALTER PROCEDURE SOFT_PRODUCT_CATEGORY_DELETE
	@CATEGORY_ID INT
AS 
BEGIN 

	UPDATE secure.PRODUCT_CATEGORIES
	SET IS_DELETED = 1
	WHERE ID = @CATEGORY_ID

	UPDATE secure.PRODUCTS
	SET IS_DELETED = 1
	WHERE @CATEGORY_ID = PRODUCT_CATEGORY_ID

END