CREATE OR ALTER TRIGGER INSTEAD_DELETE_PRODUCT_CATEGORIES_TRIGGER ON PRODUCT_CATEGORIES
INSTEAD OF DELETE
AS
BEGIN

	IF EXISTS(
		SELECT TOP 1 *
		FROM secure.PRODUCTS
		WHERE PRODUCT_CATEGORY_ID IN (SELECT ID FROM DELETED)
		)
		THROW 50001, 'UNABLE TO DELETE PRODUCT CATEGORY THAT HAS PRODUCTS', 1;

	UPDATE secure.PRODUCT_CATEGORIES
	SET IS_DELETED = 1
	WHERE ID IN (SELECT ID FROM DELETED)

END;
GO

CREATE OR ALTER TRIGGER INSTEAD_DELETE_PRODUCTS_TRIGGER ON PRODUCTS
INSTEAD OF DELETE
AS
BEGIN

	UPDATE secure.PRODUCTS
	SET IS_DELETED = 1
	WHERE ID IN (SELECT ID FROM DELETED)

END;
GO