DECLARE @L PRODUCT_LIST_TYPE;

INSERT INTO @L
VALUES (1, 10), (2, 20), (3, 10), (4, 10);

DECLARE @DATE DATETIME = GETDATE();
--EXECUTE NEW_HISTORY_EVENT @L, 1, 1, @DATE, @UPDATER = 1

EXEC NEW_SUPPLY  @L, 1, @DATE;
EXEC NEW_SALE @L, 1, @DATE;

SELECT * FROM HISTORIES
SELECT * FROM ACTUAL_FULL_HISTORY_WITH_PRODUCTS_VIEW
SELECT * FROM WAREHOUSE_PRODUCT